# Generated by Django 4.1.7 on 2023-04-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_topic_sno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='sno',
        ),
        migrations.AddField(
            model_name='webpage',
            name='email',
            field=models.EmailField(default='cricket@gmail.com', max_length=254),
        ),
    ]
